language: python
python:
  - "3.6"

matrix:
  include:
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0

      install:
        - ./prepare_deps.sh
        
      script:
        - python3 test_ffig_explorer.py
