language: python
python:
  - "3.6"

matrix:
  include:
    - os: linux
      sudo: required

      install:
        - bash ./prepare_deps.sh
        
      script:
        - python3 test_ffig_explorer.py
